# Generated by Django 3.0.3 on 2020-04-23 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=264)),
                ('User_Address', models.CharField(max_length=1000)),
                ('User_Phone', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000)])),
                ('NGO', models.CharField(max_length=264)),
                ('NGO_Address', models.CharField(max_length=264)),
                ('Things', models.CharField(max_length=1000)),
                ('Donation_Type', models.CharField(default='None', max_length=264)),
                ('Paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CreateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('NGO_name', models.CharField(max_length=264)),
                ('ThingsDonated', models.CharField(max_length=1000)),
                ('NGO_image', models.ImageField(default='images/personal2.png', upload_to='images/')),
                ('Paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonetaryCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=264)),
                ('User_Address', models.CharField(max_length=1000)),
                ('User_Phone', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1000000000)])),
                ('NGO', models.CharField(max_length=264)),
                ('NGO_Address', models.CharField(max_length=264)),
                ('Things', models.CharField(max_length=1000)),
                ('Amount', models.BigIntegerField(default=1)),
                ('Weight', models.BigIntegerField(default=1)),
                ('Paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=264)),
                ('Address', models.CharField(max_length=1000)),
                ('ThingsNeeded', models.CharField(max_length=1000)),
                ('Picture', models.ImageField(upload_to='images/')),
                ('Description', models.CharField(max_length=1000)),
                ('Phone', models.BigIntegerField()),
            ],
        ),
    ]
