# Generated by Django 3.0.3 on 2020-04-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_auto_20200424_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thingsdonated',
            old_name='user',
            new_name='collection',
        ),
    ]
